# Generated by Django 3.0.4 on 2020-04-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linked', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='category',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='linked.Category'),
            preserve_default=False,
        ),
    ]
